# Site settings
title: Krusader
email: Krusader-devel@kde.org
git: https://github.com/KDE/krusader
forum: http://forum.kde.org/viewforum.php?f=227
bugsite: https://bugs.kde.org/buglist.cgi?bug_file_loc=&amp;bug_file_loc_type=allwordssubstr&amp;bug_id=&bug_status=UNCONFIRMED&amp;bug_status=NEW&amp;bug_status=ASSIGNED&amp;bug_status=REOPENED&amp;bug_status=NEEDSINFO&amp;bug_status=VERIFIED&bugidtype=include&amp;chfieldfrom=&amp;chfieldto=Now&amp;chfieldvalue=&amp;email1=&amp;email2=&amp;emailassigned_to1=1&amp;emailassigned_to2=1&emailcc2=1&amp;emailreporter2=1&amp;emailtype1=substring&amp;emailtype2=substring&amp;field-1-0-0=product&amp;field-1-1-0=bug_status&field0-0-0=noop&amp;keywords=&amp;keywords_type=allwords&amp;long_desc=&amp;long_desc_type=substring&amp;product=krusader&query_format=advanced&amp;remaction=&amp;short_desc=&amp;short_desc_type=allwordssubstr&amp;type-1-0-0=anyexact&amp;type-1-1-0=anyexact&type0-0-0=noop&amp;value-1-0-0=krusader&amp;value-1-1-0=UNCONFIRMED%2CNEW%2CASSIGNED%2CREOPENED%2CNEEDSINFO%2CVERIFIED&amp;value0-0-0=&amp;votamp;order=bugs.bug_id%20desc&amp;query_based_on=">
bugfaq: https://docs.kde.org/trunk5/en/extragear-utils/krusader/faq_general.html

description: >
    Krusader: Twin panel file management for your desktop
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Krusader.kde.org"
twitter_username: kde_community
github_username:  kde

# Build settings
markdown: kramdown
theme: jekyll-kde-theme
sass:
  style: compressed


defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  changelogs:
    output: true

navigation:
  top:
    - title: Download
      url: /download.html
    - title: Get Involved
      url: /get-involved.html
    - title: Report Bugs
      url: /bugs.html
    - title: Documentation
      url: /documentation.html
    - title: Donate
      url: https://www.kde.org/donate
  bottom:
    - name: Community
      items:
        - title: Forum.kde.org
          url: https://forum.kde.org/viewforum.php?f=225
        - title: Phabricator Development Project
          url: https://phabricator.kde.org/tag/krusader/
        - title: CGit Repository Browser
          url: https://cgit.kde.org/krusader.git/
    - name: News &amp; Press
      items:
        - title: Announcements
          url: https://www.kde.org/announcements/
        - title: KDE.news
          url: https://dot.kde.org/
        - title: Planet KDE
          url: https://planetkde.org/
        - title: About the website 
          url: ../about/index.html
paginate: 3


exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
