# Generated by Django 2.2.7 on 2019-11-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_auto_20191109_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Recieved_kDate',
            new_name='Recieved_Date',
        ),
    ]
