# Generated by Django 2.2.7 on 2019-11-09 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.CharField(max_length=30)),
                ('itemnName', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('arriveDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickDate', models.DateTimeField(blank=True, null=True)),
                ('handedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
